name: Build and Push Docker Image with API Status Update

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: "67359e34e7298e02167e9a79"
      IMAGE_ID: "get-lines"
      IMAGE_TAG: "1"
      GIT_REPO_URL: "https://github.com/amol64546/ml-model.git"
      PATH: "/pipelines/component/src/program.py"
      SERVER_URL: "https://ig.aidtaas.com/bob-service"
      DOCKERHUB_USERNAME: "amol64546"
      DOCKERHUB_TOKEN: "dckr_pat_Snzzaoeq1bQWa_9clgOirVncSz4"

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker buildx build --push \
            --tag ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} \
            --build-arg GIT_REPO_URL=${{ env.GIT_REPO_URL }} \
            --file docker/Dockerfile \
            --platform linux/amd64,linux/arm64 .

      - name: Update Status via API
        run: |
          if [ $? -eq 0 ]; then
            response=$(curl --location --globoff --request POST "$SERVER_URL/v1.0/ml/brick/image/$IMAGE_ID?status=COMPLETED" \
              --data '' --write-out "%{http_code}" --silent --output /dev/null)
            if [[ "$response" -ge 200 && "$response" -lt 300 ]]; then
              echo "Status update: COMPLETED"
            else
              echo "API call failed with status code: $response"
            fi
          else
            response=$(curl --location --globoff --request POST "$SERVER_URL/v1.0/ml/brick/image/$IMAGE_ID?status=FAILED" \
              --data '' --write-out "%{http_code}" --silent --output /dev/null)
            if [[ "$response" -ge 200 && "$response" -lt 300 ]]; then
              echo "Status update: FAILED"
            else
              echo "API call failed with status code: $response"
            fi
          fi
