name: Build and Push Docker Image

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: "67359e34e7298e02167e9a79"                 # Set your image name
      IMAGE_ID: "get-lines"                           # Set your image ID
      IMAGE_TAG: "1"                         # Set your image tag
      GIT_REPO_URL: "https://github.com/amol64546/ml-model.git" # Set your GitHub repository URL
      PATH: "/pipelines/component/src/program.py"                        # Path to the Python script in the cloned repo
      SERVER_URL: "https://ig.aidtaas.com/bob-service"           # Server URL for API calls
      DOCKERHUB_USERNAME: "amol64546"
      DOCKERHUB_TOKEN: "dckr_pat_Snzzaoeq1bQWa_9clgOirVncSz4"

    steps:
      - name: Install tar
        run: apk update && apk add tar
        
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set executable permissions on the script
        run: chmod +x build_and_push.sh

      - name: Run the Docker build and push script
        run: ./build_and_push.sh
